### ISSUE TITLE
0.3.21 does not load: Cannot find module 'react'

### ISSUE THREAD

**Issue by kryops** [graphql/vscode-graphql#345]
## Actual Behavior

After the update to 0.3.21, the following is logged to "Output > Log (Extension Host)" when VS Code starts:

```
[2021-11-24 15:20:25.442] [exthost] [error] Activating extension GraphQL.vscode-graphql failed due to an error:
[2021-11-24 15:20:25.442] [exthost] [error] Error: Cannot find module 'react'
Require stack:
- /Users/xxx/.vscode/extensions/graphql.vscode-graphql-0.3.21/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
```

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.21
  - VSCode Version: 1.62.3
  - OS Name: MacOS
  - OS Version: 12.0.1
  - graphql config filename and format example:

Thanks for looking into it!

**Comment by ibratoev** [comment]
Same here - the extension is broken for me at the moment :(
